language: node_js
node_js:
  - "8"
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm install
script:
  - npm run linter
  - npm run build
  - npm run dev & wait-on http://localhost:4001
  - npm run test:e2e
