language: node_js
node_js:
  - '9'
cache:
  directories:
    - ~/.npm
    - ~/.cache

addons:
  sonarcloud:
    organization: "jsheroes" # the key of the organization

script:
  - cp config.example.js config.js
  - npm run linter
  - npm run build
  - npm start & wait-on http://localhost:4001
  - npm run test:e2e
  - sonar-scanner