language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - ~/.cache

script:
  - cp config/config.example.js config/config.js
  - npm run linter
  - npm run build
  - npm start & wait-on http://localhost:4001
  - npm run test:e2e
# before_deploy: npm install now --no-save # Install Now CLI on Travis
# deploy:
#   - provider: script
#     script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
#     skip_cleanup: true
#     on:
#       master: true
