language: node_js
node_js:
  - '9'
cache:
  directories:
    - ~/.npm
    - ~/.cache

script:
  - cp config/config.example.js config/config.js
  - npm run linter
  - npm run build
  - npm start & wait-on http://localhost:4001
  - npm run test:e2e
